@REM javac tage\*.java
@REM javac tage\input\*.java
@REM javac tage\input\action\*.java
@REM javac tage\networking\*.java
@REM javac tage\networking\client\*.java
@REM javac tage\networking\server\*.java
@REM javac tage\nodeControllers\*.java
@REM javac tage\shapes\*.java
@REM javac tage\objectRenderers\*.java
@REM javac tage\physics\*.java
@REM javac tage\physics\JBullet\*.java
@REM javac tage\ai\behaviortrees\*.java
@REM javac tage\audio\*.java
@REM javac tage\audio\joal\*.java
javac -Xlint:unchecked a2/*.java